[dependencies]
paste = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "store_benchmarks"
harness = false

[[bench]]
name = "timeline_benchmarks"
harness = false

[[bench]]
name = "state_mesh_benchmarks"
harness = false
